
services:

    node:
        image: node:latest
        volumes:
            - ./app/:/var/www/html/
        command: tail -f /dev/null
        working_dir: /var/www/html/
        ports:
            - "5173:5173"
        networks:
            - local-network

    redis:
        image: redis:alpine
        networks:
            - local-network

    postgres:
        image: 'postgres:15-alpine'
        volumes:
            - 'postgresdata:/var/lib/postgres'
        ports:
            - '8084:5432'
        restart: 'unless-stopped'
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        networks:
            - local-network

    pgadmin:
        user: root
        image: dpage/pgadmin4:latest
        depends_on:
            - postgres
        environment:
          PGADMIN_DEFAULT_EMAIL: user@localhost.com
          PGADMIN_DEFAULT_PASSWORD: password
        ports:
            - 8088:80
        volumes:
            - .postgresql:/var/lib/postgresql/data
        networks:
            - local-network

    webserver:
        image: 'nginx:alpine'
        ports:
            - '8080:80'
        volumes:
           - './app/public:/var/www/html/public'
           - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        networks:
            - local-network

    php-fpm:
        build: 
            dockerfile: ./docker/php/Dockerfile
            target: app_dev
        volumes:
            - './app:/var/www/html'
            - './docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro'
        environment:
            - POSTGRES_HOST=postgres
            - POSTGRES_PORT=${POSTGRES_PORT}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
            - REDIS_HOST=redis
            - REDIS_PORT=${REDIS_PORT}
            - XDEBUG_MODE:'${XDEBUG_MODE:-debug}'
        extra_hosts:
            - host.docker.internal:host-gateway
        networks:
            - local-network

volumes:
    postgresdata:
    postgresql:

networks:
    local-network:
        external: false